version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - FLASK_PORT=${FLASK_CONTAINER_PORT}
    ports:
      - ${HOST_PORT}:${FLASK_CONTAINER_PORT}

