# File: .github/workflows/workflow.yml

on: [push]

name: SampleWorkflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}    
        
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
