# File: .github/workflows/azure.yml
# tags: [ 'v*.*.*' ]

name: SampleWorkflowUsingAzure

on: 
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main      
  workflow_dispatch:
    
permissions:
      id-token: write
      contents: read
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DEVELOPMENT    
    steps:
      - name: 'Checkout Github repo'
        uses: actions/checkout@v3
          
      - name: 'Login via Az module'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Get Azure KeyVault secrets'   
        uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: ${{ secrets.AZURE_KEYVAULT }}
          secrets: 'AZURE-CONTAINER-REPO-Username, AZURE-CONTAINER-REPO-Password'
        id: azkv_GetSecrets

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
          tags: type=sha

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
        
      - name: 'Connect to docker'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ steps.azkv_GetSecrets.outputs.AZURE-CONTAINER-REPO-Username }}
          password: ${{ steps.azkv_GetSecrets.outputs.AZURE-CONTAINER-REPO-Password }}      
          
      - name: 'Lowercase the repo name'
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: 'Build and push docker container to registry'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }} ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.REPO }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}          
