# File: .github/workflows/workflow.yml

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main      
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

name: SampleWorkflowUsingAzure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DEVELOPMENT    
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd 
