# File: .github/workflows/workflow.yml

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main      
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

name: SampleWorkflowUsingAzure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DEVELOPMENT    
    steps:
      - name: 'Checkout Github repo'
        uses: actions/checkout@v2
          
      - name: 'Login via Az module'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Get Azure KeyVault secrets'   
        uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: ${{ secrets.AZURE_KEYVAULT }}
          secrets: 'AZURE-CONTAINER-REPO-Username, AZURE-CONTAINER-REPO-Password'
        id: azkv_GetSecrets
      
      - name: 'Run az commands'
        run: |
          echo ${{ steps.azkv_GetSecrets.outputs.AZURE-CONTAINER-REPO-Username }}
          echo ${{ steps.azkv_GetSecrets.outputs.AZURE-CONTAINER-REPO-Password }}
          az account show
          az group list
          pwd 
        
      - name: 'Connect to docker'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ steps.azkv_GetSecrets.outputs.AZURE-CONTAINER-REPO-Username }}
          password: ${{ steps.azkv_GetSecrets.outputs.AZURE-CONTAINER-REPO-Password }}      
          
      - name: 'List contents of Docker container registry'
        run: |
          docker ps --all
          docker images --all
